### ISSUE TITLE
HELP!!!!!!

### ISSUE THREAD

**Issue by iatomic1** [udecode/plate-playground#12]
Someone should pls help me on how to get the value of the editor
I added an onChange prop to plate-editor and passed a setState to the onChange in the parent component but it keeps rerendering and the Plate component from `@usecode/plate-common/react` doesn't accept a value prop which would fix that

**Comment by zbeyens** [comment]
Please read the docs.

**Comment by iatomic1** [comment]
> Please read the docs.

I have 😭

**Comment by zbeyens** [comment]
This one https://platejs.org/docs/controlled

**Comment by iatomic1** [comment]
> This one https://platejs.org/docs/controlled

Yes, it doesn't have a get
