### ISSUE TITLE
Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.

### ISSUE THREAD

**Issue by linhme711** [udecode/plate-playground#2]
When I first initialize and run the project, there's an warning error in the console.

![image](https://github.com/udecode/plate-playground-template/assets/137847954/66ae4753-e88a-4678-8379-ad216fba1347)

**Comment by inapeace0** [comment]
Hi, I got the same issue.
But didn't figure out it yet. 😉

**Comment by gulfaraz** [comment]
@linhme711 @CaCaBlocker 

Try adding `asChild` to `TooltipTrigger` in [toolbar.tsx](https://github.com/udecode/plate-playground-template/blob/e9d773b6642f4d580af44a6d845905b22e0253c1/src/components/plate-ui/toolbar.tsx#L149)
```
-        <TooltipTrigger>{content}</TooltipTrigger>
+        <TooltipTrigger asChild>{content}</TooltipTrigger>
```
